#!/usr/bin/env bash
# apply-pr8.sh
# Usage: run from the root of SolanaRemix/castquest-frames
set -euo pipefail

BRANCH="feat/openapi-sdk-migrations"
COMMIT_MSG="Add OpenAPI spec, TypeScript SDK starter, and initial DB migrations (PR #8)"
PR_TITLE="Add full OpenAPI spec, TypeScript SDK starter, and initial DB migrations"
PR_BODY_FILE="PR_DESCRIPTION.md"
PATCH_FILE="pr8.patch"

# 1) ensure we are in a git repository root
if ! git rev-parse --show-toplevel >/dev/null 2>&1; then
  echo "Error: not in a git repository. Run this from the repo root."
  exit 1
fi

# 2) ensure working tree is clean
if [[ -n "$(git status --porcelain)" ]]; then
  echo "Your working tree is not clean. Please commit or stash changes first."
  git status --porcelain
  exit 1
fi

# 3) write the patch to a file (the patch below was generated by Copilot)
cat > "$PATCH_FILE" <<'PATCH'
*** Begin Patch
*** Add File: infra/openapi/castquest-full-openapi.yaml
+openapi: "3.0.3"
+info:
+  title: CastQuest - Full API (expanded)
+  version: "1.0.0"
+  description: |
+    Expanded OpenAPI 3.0.3 specification for CastQuest microservices.
+    Covers auth, projects, frames, ai, market, quests, social, admin, analytics, dev-api, agents, shipments, billing.
+    Use this file as the source of truth to generate SDKs and docs.
+servers:
+  - url: https://api.castquest.io
+    description: Production
+  - url: http://localhost:8080
+    description: Local api-gateway
+
+security:
+  - bearerAuth: []
+
+tags:
+  - name: auth
+    description: Authentication, sessions and API keys
+  - name: projects
+    description: Projects, files and previews
+  - name: frames
+    description: Frame templates, versions, Farcaster integration, timelines
+  - name: ai
+    description: AI orchestrator and jobs
+  - name: market
+    description: Marketplace listings & buy flows
+  - name: quests
+    description: Quests, achievements, leaderboard
+  - name: social
+    description: Feed, profiles, follows, likes
+  - name: admin
+    description: Admin-only endpoints and governance
+  - name: analytics
+    description: Dashboard & metrics
+  - name: dev-api
+    description: API portal, SDKs and pipelines
+  - name: agents
+    description: Agents lifecycle and configs
+  - name: shipments
+    description: Shipment / deployment flows
+  - name: billing
+    description: Subscriptions and invoices
+
+paths:
+  /auth/signup:
+    post:
+      tags: [auth]
+      summary: Sign up and create (or join) a tenant
+      requestBody:
+        required: true
+        content:
+          application/json:
+            schema:
+              $ref: '#/components/schemas/AuthSignup'
+      responses:
+        '201':
+          description: Created - returns tokens and user
+          content:
+            application/json:
+              schema:
+                $ref: '#/components/schemas/AuthTokenResponse'
+        '400':
+          $ref: '#/components/responses/BadRequest'
+
+  /auth/login/passwordless/request:
+    post:
+      tags: [auth]
+      summary: Request passwordless magic link
+      requestBody:
+        required: true
+        content:
+          application/json:
+            schema:
+              type: object
+              required: [email]
+              properties:
+                email:
+                  type: string
+      responses:
+        '202':
+          description: Accepted (magic link sent)
+        '400':
+          $ref: '#/components/responses/BadRequest'
+
+  /auth/login/passwordless/verify:
+    post:
+      tags: [auth]
+      summary: Verify magic link and obtain tokens
+      requestBody:
+        required: true
+        content:
+          application/json:
+            schema:
+              type: object
+              required: [token]
+              properties:
+                token:
+                  type: string
+      responses:
+        '200':
+          description: Tokens issued
+          content:
+            application/json:
+              schema:
+                $ref: '#/components/schemas/AuthTokenResponse'
+        '401':
+          $ref: '#/components/responses/Unauthorized'
+
+  /auth/me:
+    get:
+      tags: [auth]
+      summary: Get current authenticated user and tenant
+      security:
+        - bearerAuth: []
+      responses:
+        '200':
+          description: Current user and tenant
+          content:
+            application/json:
+              schema:
+                type: object
+                properties:
+                  user:
+                    $ref: '#/components/schemas/User'
+                  tenant:
+                    $ref: '#/components/schemas/Tenant'
+        '401':
+          $ref: '#/components/responses/Unauthorized'
+
+  /auth/token/refresh:
+    post:
+      tags: [auth]
+      summary: Exchange refresh token for new access token
+      requestBody:
+        required: true
+        content:
+          application/json:
+            schema:
+              type: object
+              required: [refreshToken]
+              properties:
+                refreshToken:
+                  type: string
+      responses:
+        '200':
+          description: New tokens
+          content:
+            application/json:
+              schema:
+                $ref: '#/components/schemas/AuthTokenResponse'
+        '401':
+          $ref: '#/components/responses/Unauthorized'
+
+  /auth/logout:
+    post:
+      tags: [auth]
+      summary: Revoke refresh token / logout
+      security:
+        - bearerAuth: []
+      responses:
+        '204':
+          description: Logged out
+
+  /auth/api-keys:
+    post:
+      tags: [auth]
+      summary: Create API key for tenant
+      security:
+        - bearerAuth: []
+      requestBody:
+        required: true
+        content:
+          application/json:
+            schema:
+              type: object
+              required: [name, scopes]
+              properties:
+                name: { type: string }
+                scopes:
+                  type: array
+                  items: { type: string }
+      responses:
+        '201':
+          description: API key created - plaintext secret returned once
+          content:
+            application/json:
+              schema:
+                $ref: '#/components/schemas/ApiKeyCreateResponse'
+    get:
+      tags: [auth]
+      summary: List API keys
+      security:
+        - bearerAuth: []
+      responses:
+        '200':
+          description: List of API keys
+          content:
+            application/json:
+              schema:
+                type: array
+                items:
+                  $ref: '#/components/schemas/ApiKey'
+
+  /projects:
+    get:
+      tags: [projects]
+      summary: List tenant projects
+      security:
+        - bearerAuth: []
+      parameters:
+        - name: limit
+          in: query
+          schema: { type: integer, default: 20 }
+        - name: offset
+          in: query
+          schema: { type: integer, default: 0 }
+      responses:
+        '200':
+          description: Projects page
+          content:
+            application/json:
+              schema:
+                $ref: '#/components/schemas/PaginatedProjects'
+    post:
+      tags: [projects]
+      summary: Create a new project
+      security:
+        - bearerAuth: []
+      requestBody:
+        required: true
+        content:
+          application/json:
+            schema:
+              $ref: '#/components/schemas/ProjectCreate'
+      responses:
+        '201':
+          description: Created project
+          content:
+            application/json:
+              schema:
+                $ref: '#/components/schemas/Project'
+
+  /projects/{projectId}:
+    get:
+      tags: [projects]
+      summary: Get project by id
+      security:
+        - bearerAuth: []
+      parameters:
+        - name: projectId
+          in: path
+          required: true
+          schema: { type: string, format: uuid }
+      responses:
+        '200':
+          description: Project object
+          content:
+            application/json:
+              schema:
+                $ref: '#/components/schemas/Project'
+        '404':
+          $ref: '#/components/responses/NotFound'
+    patch:
+      tags: [projects]
+      summary: Update project
+      security:
+        - bearerAuth: []
+      parameters:
+        - name: projectId
+          in: path
+          required: true
+          schema: { type: string, format: uuid }
+      requestBody:
+        content:
+          application/json:
+            schema:
+              $ref: '#/components/schemas/ProjectUpdate'
+      responses:
+        '200':
+          description: Updated
+          content:
+            application/json:
+              schema:
+                $ref: '#/components/schemas/Project'
+
+  /projects/{projectId}/files:
+    get:
+      tags: [projects]
+      summary: List files under project path or tree
+      security:
+        - bearerAuth: []
+      parameters:
+        - name: projectId
+          in: path
+          required: true
+          schema: { type: string, format: uuid }
+        - name: path
+          in: query
+          schema: { type: string }
+      responses:
+        '200':
+          description: Files array
+          content:
+            application/json:
+              schema:
+                type: array
+                items:
+                  $ref: '#/components/schemas/File'
+    post:
+      tags: [projects]
+      summary: Create a file or directory
+      security:
+        - bearerAuth: []
+      parameters:
+        - name: projectId
+          in: path
+          required: true
+          schema: { type: string, format: uuid }
+      requestBody:
+        required: true
+        content:
+          application/json:
+            schema:
+              $ref: '#/components/schemas/FileCreate'
+      responses:
+        '201':
+          description: File created
+          content:
+            application/json:
+              schema:
+                $ref: '#/components/schemas/File'
+
+  /projects/{projectId}/files/{fileId}:
+    get:
+      tags: [projects]
+      summary: Get file content by id
+      security:
+        - bearerAuth: []
+      parameters:
+        - name: projectId
+          in: path
+          required: true
+          schema: { type: string, format: uuid }
+        - name: fileId
+          in: path
+          required: true
+          schema: { type: string, format: uuid }
+      responses:
+        '200':
+          description: File object
+          content:
+            application/json:
+              schema:
+                $ref: '#/components/schemas/File'
+        '404':
+          $ref: '#/components/responses/NotFound'
+    patch:
+      tags: [projects]
+      summary: Update file content or path
+      security:
+        - bearerAuth: []
+      parameters:
+        - name: projectId
+          in: path
+          required: true
+          schema: { type: string, format: uuid }
+        - name: fileId
+          in: path
+          required: true
+          schema: { type: string, format: uuid }
+      requestBody:
+        content:
+          application/json:
+            schema:
+              $ref: '#/components/schemas/FileUpdate'
+      responses:
+        '200':
+          description: Updated file
+          content:
+            application/json:
+              schema:
+                $ref: '#/components/schemas/File'
+
+  /projects/{projectId}/preview/build:
+    post:
+      tags: [projects]
+      summary: Trigger preview build (emit event)
+      security:
+        - bearerAuth: []
+      parameters:
+        - name: projectId
+          in: path
+          required: true
+          schema: { type: string, format: uuid }
+      requestBody:
+        content:
+          application/json:
+            schema:
+              type: object
+              properties:
+                branch: { type: string }
+                commitId: { type: string }
+      responses:
+        '202':
+          description: Build queued
+          content:
+            application/json:
+              schema:
+                type: object
+                properties:
+                  previewId: { type: string, format: uuid }
+                  status: { type: string, example: "queued" }
+
+  /frames/templates:
+    get:
+      tags: [frames]
+      summary: List frame templates
+      security:
+        - bearerAuth: []
+      parameters:
+        - name: projectId
+          in: query
+          schema: { type: string, format: uuid }
+        - name: creatorId
+          in: query
+          schema: { type: string, format: uuid }
+        - name: search
+          in: query
+          schema: { type: string }
+        - name: category
+          in: query
+          schema: { type: string }
+        - name: isPublic
+          in: query
+          schema: { type: boolean }
+      responses:
+        '200':
+          description: Templates list
+          content:
+            application/json:
+              schema:
+                $ref: '#/components/schemas/PaginatedFrameTemplates'
+    post:
+      tags: [frames]
+      summary: Create a new frame template
+      security:
+        - bearerAuth: []
+      requestBody:
+        content:
+          application/json:
+            schema:
+              $ref: '#/components/schemas/FrameTemplateCreate'
+      responses:
+        '201':
+          description: Template created
+          content:
+            application/json:
+              schema:
+                $ref: '#/components/schemas/FrameTemplate'
+
+  /frames/templates/{templateId}:
+    get:
+      tags: [frames]
+      summary: Get frame template
+      parameters:
+        - name: templateId
+          in: path
+          required: true
+          schema: { type: string, format: uuid }
+      responses:
+        '200':
+          description: Template
+          content:
+            application/json:
+              schema:
+                $ref: '#/components/schemas/FrameTemplate'
+        '404':
+          $ref: '#/components/responses/NotFound'
+    patch:
+      tags: [frames]
+      summary: Update template metadata
+      security:
+        - bearerAuth: []
+      requestBody:
+        content:
+          application/json:
+            schema:
+              $ref: '#/components/schemas/FrameTemplateUpdate'
+      responses:
+        '200':
+          description: Updated
+          content:
+            application/json:
+              schema:
+                $ref: '#/components/schemas/FrameTemplate'
+    delete:
+      tags: [frames]
+      summary: Delete a template
+      security:
+        - bearerAuth: []
+      responses:
+        '204':
+          description: Deleted
+
+  /frames/templates/{templateId}/versions:
+    get:
+      tags: [frames]
+      summary: List versions for a template
+      parameters:
+        - name: templateId
+          in: path
+          required: true
+          schema: { type: string, format: uuid }
+      responses:
+        '200':
+          description: Versions array
+          content:
+            application/json:
+              schema:
+                type: array
+                items:
+                  $ref: '#/components/schemas/FrameTemplateVersion'
+    post:
+      tags: [frames]
+      summary: Create a new template version
+      security:
+        - bearerAuth: []
+      requestBody:
+        content:
+          application/json:
+            schema:
+              $ref: '#/components/schemas/FrameTemplateVersionCreate'
+      responses:
+        '201':
+          description: Version created
+          content:
+            application/json:
+              schema:
+                $ref: '#/components/schemas/FrameTemplateVersion'
+
+  /frames/templates/{templateId}/deploy:
+    post:
+      tags: [frames]
+      summary: Deploy a template version (async) — emits frame.deploy.request
+      security:
+        - bearerAuth: []
+      parameters:
+        - name: templateId
+          in: path
+          required: true
+          schema: { type: string, format: uuid }
+      requestBody:
+        required: true
+        content:
+          application/json:
+            schema:
+              type: object
+              required: [versionId]
+              properties:
+                versionId: { type: string, format: uuid }
+                network: { type: string }
+                farcasterConfig: { type: object }
+                notes: { type: string }
+      responses:
+        '202':
+          description: Deploy queued
+          content:
+            application/json:
+              schema:
+                type: object
+                properties:
+                  requestId: { type: string, format: uuid }
+                  status: { type: string, example: "queued" }
+        '400':
+          $ref: '#/components/responses/BadRequest'
+
+  /frames/templates/{templateId}/revert:
+    post:
+      tags: [frames]
+      summary: Revert template to a target version (creates timeline entry)
+      security:
+        - bearerAuth: []
+      parameters:
+        - name: templateId
+          in: path
+          required: true
+          schema: { type: string, format: uuid }
+      requestBody:
+        required: true
+        content:
+          application/json:
+            schema:
+              type: object
+              required: [targetVersionId]
+              properties:
+                targetVersionId: { type: string, format: uuid }
+                reason: { type: string }
+      responses:
+        '200':
+          description: Revert accepted, timeline updated
+          content:
+            application/json:
+              schema:
+                $ref: '#/components/schemas/FrameTimeline'
+
+  /ai/jobs:
+    post:
+      tags: [ai]
+      summary: Create AI job (queued)
+      security:
+        - bearerAuth: []
+      requestBody:
+        required: true
+        content:
+          application/json:
+            schema:
+              $ref: '#/components/schemas/AiJobCreate'
+      responses:
+        '201':
+          description: Job created (queued)
+          content:
+            application/json:
+              schema:
+                $ref: '#/components/schemas/AiJob'
+    get:
+      tags: [ai]
+      summary: List AI jobs (filterable)
+      security:
+        - bearerAuth: []
+      parameters:
+        - name: projectId
+          in: query
+          schema: { type: string, format: uuid }
+        - name: status
+          in: query
+          schema: { type: string }
+        - name: limit
+          in: query
+          schema: { type: integer, default: 20 }
+        - name: offset
+          in: query
+          schema: { type: integer, default: 0 }
+      responses:
+        '200':
+          description: Jobs page
+          content:
+            application/json:
+              schema:
+                type: object
+                properties:
+                  items:
+                    type: array
+                    items:
+                      $ref: '#/components/schemas/AiJob'
+                  total: { type: integer }
+
+  /ai/jobs/{jobId}:
+    get:
+      tags: [ai]
+      summary: Get AI job by id
+      security:
+        - bearerAuth: []
+      parameters:
+        - name: jobId
+          in: path
+          required: true
+          schema: { type: string, format: uuid }
+      responses:
+        '200':
+          description: AI job
+          content:
+            application/json:
+              schema:
+                $ref: '#/components/schemas/AiJob'
+        '404':
+          $ref: '#/components/responses/NotFound'
+
+  /market/listings:
+    get:
+      tags: [market]
+      summary: Browse marketplace listings
+      parameters:
+        - name: category
+          in: query
+          schema: { type: string }
+        - name: limit
+          in: query
+          schema: { type: integer, default: 20 }
+        - name: offset
+          in: query
+          schema: { type: integer, default: 0 }
+      responses:
+        '200':
+          description: Listings page
+          content:
+            application/json:
+              schema:
+                type: object
+                properties:
+                  items:
+                    type: array
+                    items:
+                      $ref: '#/components/schemas/MarketListing'
+                  total:
+                    type: integer
+    post:
+      tags: [market]
+      summary: Create a marketplace listing
+      security:
+        - bearerAuth: []
+      requestBody:
+        required: true
+        content:
+          application/json:
+            schema:
+              $ref: '#/components/schemas/MarketListingCreate'
+      responses:
+        '201':
+          description: Listing created
+          content:
+            application/json:
+              schema:
+                $ref: '#/components/schemas/MarketListing'
+
+  /market/listings/{id}/buy:
+    post:
+      tags: [market]
+      summary: Initiate buy flow (returns contract payloads)
+      security:
+        - bearerAuth: []
+      parameters:
+        - name: id
+          in: path
+          required: true
+          schema: { type: string, format: uuid }
+      responses:
+        '200':
+          description: Buy flow payloads
+          content:
+            application/json:
+              schema:
+                type: object
+                properties:
+                  contractCallPayload:
+                    type: object
+                  orderId:
+                    type: string
+        '400':
+          $ref: '#/components/responses/BadRequest'
+
+  /quests/active:
+    get:
+      tags: [quests]
+      summary: List active quests
+      responses:
+        '200':
+          description: Active quests
+          content:
+            application/json:
+              schema:
+                type: array
+                items:
+                  $ref: '#/components/schemas/Quest'
+
+  /quests/{questId}/claim:
+    post:
+      tags: [quests]
+      summary: Claim quest reward (if eligible)
+      security:
+        - bearerAuth: []
+      parameters:
+        - name: questId
+          in: path
+          required: true
+          schema: { type: string, format: uuid }
+      responses:
+        '200':
+          description: Claimed (awarded)
+          content:
+            application/json:
+              schema:
+                type: object
+                properties:
+                  awarded: { type: boolean }
+        '400':
+          $ref: '#/components/responses/BadRequest'
+
+  /social/feed:
+    get:
+      tags: [social]
+      summary: Get global or personalized feed
+      parameters:
+        - name: cursor
+          in: query
+          schema: { type: string }
+        - name: followingOnly
+          in: query
+          schema: { type: boolean }
+      responses:
+        '200':
+          description: Feed page
+          content:
+            application/json:
+              schema:
+                type: object
+                properties:
+                  items:
+                    type: array
+                    items:
+                      $ref: '#/components/schemas/FeedItem'
+                  nextCursor: { type: string }
+
+  /profiles/{handle}:
+    get:
+      tags: [social]
+      summary: Get profile by handle
+      parameters:
+        - name: handle
+          in: path
+          required: true
+          schema: { type: string }
+      responses:
+        '200':
+          description: Profile + summary
+          content:
+            application/json:
+              schema:
+                type: object
+                properties:
+                  user: { $ref: '#/components/schemas/User' }
+                  framesCount: { type: integer }
+                  followersCount: { type: integer }
+                  followingCount: { type: integer }
+
+  /admin/tenants:
+    get:
+      tags: [admin]
+      summary: List tenants (admin only)
+      security:
+        - bearerAuth: []
+      responses:
+        '200':
+          description: Tenants list
+          content:
+            application/json:
+              schema:
+                type: array
+                items:
+                  $ref: '#/components/schemas/Tenant'
+
+  /admin/audit-logs:
+    get:
+      tags: [admin]
+      summary: Search audit logs
+      security:
+        - bearerAuth: []
+      parameters:
+        - name: tenantId
+          in: query
+          schema: { type: string, format: uuid }
+        - name: action
+          in: query
+          schema: { type: string }
+        - name: entityType
+          in: query
+          schema: { type: string }
+        - name: limit
+          in: query
+          schema: { type: integer, default: 50 }
+      responses:
+        '200':
+          description: Audit logs page
+          content:
+            application/json:
+              schema:
+                type: array
+                items:
+                  $ref: '#/components/schemas/AuditLog'
+
+  /analytics/overview:
+    get:
+      tags: [analytics]
+      summary: Overview metrics for dashboards
+      security:
+        - bearerAuth: []
+      responses:
+        '200':
+          description: Overview metrics
+          content:
+            application/json:
+              schema:
+                $ref: '#/components/schemas/AnalyticsOverview'
+
+  /dev-api/docs:
+    get:
+      tags: [dev-api]
+      summary: List available OpenAPI specs & docs
+      responses:
+        '200':
+          description: Docs metadata
+          content:
+            application/json:
+              schema:
+                type: array
+                items:
+                  type: object
+                  properties:
+                    service: { type: string }
+                    openapiUrl: { type: string }
+
+  /agents:
+    get:
+      tags: [agents]
+      summary: List agents
+      security:
+        - bearerAuth: []
+      responses:
+        '200':
+          description: Agents list
+          content:
+            application/json:
+              schema:
+                type: array
+                items:
+                  $ref: '#/components/schemas/Agent'
+    post:
+      tags: [agents]
+      summary: Create agent
+      security:
+        - bearerAuth: []
+      requestBody:
+        content:
+          application/json:
+            schema:
+              $ref: '#/components/schemas/AgentCreate'
+      responses:
+        '201':
+          description: Created
+          content:
+            application/json:
+              schema:
+                $ref: '#/components/schemas/Agent'
+
+  /shipments:
+    get:
+      tags: [shipments]
+      summary: List shipments
+      security:
+        - bearerAuth: []
+      parameters:
+        - name: projectId
+          in: query
+          schema: { type: string, format: uuid }
+      responses:
+        '200':
+          description: Shipments
+          content:
+            application/json:
+              schema:
+                type: array
+                items:
+                  $ref: '#/components/schemas/Shipment'
+    post:
+      tags: [shipments]
+      summary: Create shipment (emit shipment.created)
+      security:
+        - bearerAuth: []
+      requestBody:
+        content:
+          application/json:
+            schema:
+              $ref: '#/components/schemas/ShipmentCreate'
+      responses:
+        '201':
+          description: Created
+          content:
+            application/json:
+              schema:
+                $ref: '#/components/schemas/Shipment'
+
+  /billing/summary:
+    get:
+      tags: [billing]
+      summary: Get billing summary for tenant
+      security:
+        - bearerAuth: []
+      responses:
+        '200':
+          description: Billing summary
+          content:
+            application/json:
+              schema:
+                $ref: '#/components/schemas/BillingSummary'
+
+components:
+  responses:
+    BadRequest:
+      description: Bad request
+      content:
+        application/json:
+          schema:
+            $ref: '#/components/schemas/ErrorResponse'
+    Unauthorized:
+      description: Unauthorized
+      content:
+        application/json:
+          schema:
+            $ref: '#/components/schemas/ErrorResponse'
+    NotFound:
+      description: Not found
+      content:
+        application/json:
+          schema:
+            $ref: '#/components/schemas/ErrorResponse'
+
+  securitySchemes:
+    bearerAuth:
+      type: http
+      scheme: bearer
+      bearerFormat: JWT
+    ApiKeyAuth:
+      type: apiKey
+      in: header
+      name: X-API-Key
+
+  schemas:
+    ErrorResponse:
+      type: object
+      properties:
+        error:
+          type: string
+        message:
+          type: string
+        details:
+          type: object
+      example:
+        error: "BadRequest"
+        message: "Missing required field 'name'"
+
+    UUID:
+      type: string
+      format: uuid
+
+    Pagination:
+      type: object
+      properties:
+        limit: { type: integer }
+        offset: { type: integer }
+        total: { type: integer }
+
+    Tenant:
+      type: object
+      properties:
+        id: { $ref: '#/components/schemas/UUID' }
+        slug: { type: string }
+        name: { type: string }
+        plan: { type: string }
+        created_at: { type: string, format: date-time }
+        updated_at: { type: string, format: date-time }
+
+    User:
+      type: object
+      properties:
+        id: { $ref: '#/components/schemas/UUID' }
+        tenant_id: { $ref: '#/components/schemas/UUID' }
+        email: { type: string, format: email }
+        username: { type: string }
+        display_name: { type: string }
+        avatar_url: { type: string }
+        bio: { type: string }
+        role: { type: string }
+        github_id: { type: string, nullable: true }
+        wallet_address: { type: string, nullable: true }
+        created_at: { type: string, format: date-time }
+        updated_at: { type: string, format: date-time }
+
+    Session:
+      type: object
+      properties:
+        id: { $ref: '#/components/schemas/UUID' }
+        user_id: { $ref: '#/components/schemas/UUID' }
+        refresh_token_hash: { type: string }
+        expires_at: { type: string, format: date-time }
+        user_agent: { type: string }
+        ip: { type: string, format: ipv4 }
+
+    ApiKey:
+      type: object
+      properties:
+        id: { $ref: '#/components/schemas/UUID' }
+        tenant_id: { $ref: '#/components/schemas/UUID' }
+        user_id: { $ref: '#/components/schemas/UUID' }
+        name: { type: string }
+        prefix: { type: string }
+        scopes:
+          type: array
+          items: { type: string }
+        last_used_at: { type: string, format: date-time }
+        revoked_at: { type: string, nullable: true }
+        created_at: { type: string, format: date-time }
+
+    ApiKeyCreateResponse:
+      type: object
+      properties:
+        id: { $ref: '#/components/schemas/UUID' }
+        prefix: { type: string }
+        secretPlaintext: { type: string }
+
+    AuthSignup:
+      type: object
+      properties:
+        email: { type: string }
+        username: { type: string }
+        tenantSlug: { type: string }
+      required: [email]
+
+    AuthTokenResponse:
+      type: object
+      properties:
+        accessToken: { type: string }
+        refreshToken: { type: string }
+        user:
+          $ref: '#/components/schemas/User'
+        tenant:
+          $ref: '#/components/schemas/Tenant'
+
+    Project:
+      type: object
+      properties:
+        id: { $ref: '#/components/schemas/UUID' }
+        tenant_id: { $ref: '#/components/schemas/UUID' }
+        owner_id: { $ref: '#/components/schemas/UUID' }
+        name: { type: string }
+        slug: { type: string }
+        description: { type: string }
+        visibility: { type: string, enum: [private, team, public] }
+        default_branch: { type: string }
+        created_at: { type: string, format: date-time }
+        updated_at: { type: string, format: date-time }
+
+    ProjectCreate:
+      type: object
+      required: [name]
+      properties:
+        name: { type: string }
+        description: { type: string }
+        visibility: { type: string, enum: [private, team, public] }
+
+    ProjectUpdate:
+      type: object
+      properties:
+        name: { type: string }
+        description: { type: string }
+        visibility: { type: string }
+
+    PaginatedProjects:
+      type: object
+      properties:
+        items:
+          type: array
+          items:
+            $ref: '#/components/schemas/Project'
+        total: { type: integer }
+
+    File:
+      type: object
+      properties:
+        id: { $ref: '#/components/schemas/UUID' }
+        tenant_id: { $ref: '#/components/schemas/UUID' }
+        project_id: { $ref: '#/components/schemas/UUID' }
+        path: { type: string }
+        content: { type: string, nullable: true }
+        language: { type: string, nullable: true }
+        version: { type: integer }
+        is_directory: { type: boolean }
+        parent_id: { $ref: '#/components/schemas/UUID', nullable: true }
+        created_at: { type: string, format: date-time }
+        updated_at: { type: string, format: date-time }
+
+    FileCreate:
+      type: object
+      required: [path]
+      properties:
+        path: { type: string }
+        content: { type: string }
+        language: { type: string }
+        isDirectory: { type: boolean }
+        parentId: { $ref: '#/components/schemas/UUID' }
+
+    FileUpdate:
+      type: object
+      properties:
+        path: { type: string }
+        content: { type: string }
+        language: { type: string }
+
+    FileSnapshot:
+      type: object
+      properties:
+        id: { $ref: '#/components/schemas/UUID' }
+        file_id: { $ref: '#/components/schemas/UUID' }
+        version: { type: integer }
+        content: { type: string }
+        created_at: { type: string, format: date-time }
+        created_by: { $ref: '#/components/schemas/UUID' }
+
+    Preview:
+      type: object
+      properties:
+        id: { $ref: '#/components/schemas/UUID' }
+        project_id: { $ref: '#/components/schemas/UUID' }
+        compiled_bundle_url: { type: string }
+        iframe_url: { type: string }
+        last_build_status: { type: string }
+        last_build_log: { type: string }
+        created_at: { type: string, format: date-time }
+        updated_at: { type: string, format: date-time }
+
+    FrameTemplate:
+      type: object
+      properties:
+        id: { $ref: '#/components/schemas/UUID' }
+        tenant_id: { $ref: '#/components/schemas/UUID' }
+        project_id: { $ref: '#/components/schemas/UUID' }
+        name: { type: string }
+        slug: { type: string, nullable: true }
+        description: { type: string }
+        category: { type: string }
+        current_version_id: { $ref: '#/components/schemas/UUID', nullable: true }
+        farcaster_frame_id: { type: string, nullable: true }
+        is_public: { type: boolean }
+        price_wei: { type: string, nullable: true }
+        royalty_bps: { type: integer, nullable: true }
+        created_by: { $ref: '#/components/schemas/UUID' }
+        created_at: { type: string, format: date-time }
+        updated_at: { type: string, format: date-time }
+
+    FrameTemplateCreate:
+      type: object
+      required: [projectId, name, initialSchema]
+      properties:
+        projectId: { $ref: '#/components/schemas/UUID' }
+        name: { type: string }
+        description: { type: string }
+        category: { type: string }
+        initialSchema: { type: object }
+        isPublic: { type: boolean }
+        priceWei: { type: string }
+        royaltyBps: { type: integer }
+
+    FrameTemplateUpdate:
+      type: object
+      properties:
+        name: { type: string }
+        description: { type: string }
+        category: { type: string }
+        isPublic: { type: boolean }
+        priceWei: { type: string }
+        royaltyBps: { type: integer }
+
+    FrameTemplateVersion:
+      type: object
+      properties:
+        id: { $ref: '#/components/schemas/UUID' }
+        template_id: { $ref: '#/components/schemas/UUID' }
+        version: { type: integer }
+        schema: { type: object }
+        status: { type: string }
+        change_summary: { type: string }
+        created_by: { $ref: '#/components/schemas/UUID' }
+        created_at: { type: string, format: date-time }
+
+    FrameTemplateVersionCreate:
+      type: object
+      required: [schema]
+      properties:
+        schema: { type: object }
+        changeSummary: { type: string }
+
+    FrameTimeline:
+      type: object
+      properties:
+        id: { $ref: '#/components/schemas/UUID' }
+        tenant_id: { $ref: '#/components/schemas/UUID' }
+        template_id: { $ref: '#/components/schemas/UUID' }
+        version_id: { $ref: '#/components/schemas/UUID', nullable: true }
+        event_type: { type: string }
+        metadata: { type: object }
+        created_at: { type: string, format: date-time }
+        created_by: { $ref: '#/components/schemas/UUID' }
+
+    Agent:
+      type: object
+      properties:
+        id: { $ref: '#/components/schemas/UUID' }
+        tenant_id: { $ref: '#/components/schemas/UUID' }
+        name: { type: string }
+        description: { type: string }
+        type: { type: string }
+        config: { type: object }
+        is_active: { type: boolean }
+        created_at: { type: string, format: date-time }
+        updated_at: { type: string, format: date-time }
+
+    AgentCreate:
+      type: object
+      required: [name, type]
+      properties:
+        name: { type: string }
+        description: { type: string }
+        type: { type: string }
+        config: { type: object }
+
+    Shipment:
+      type: object
+      properties:
+        id: { $ref: '#/components/schemas/UUID' }
+        tenant_id: { $ref: '#/components/schemas/UUID' }
+        project_id: { $ref: '#/components/schemas/UUID' }
+        agent_id: { $ref: '#/components/schemas/UUID', nullable: true }
+        status: { type: string }
+        target_env: { type: string }
+        payload: { type: object }
+        result: { type: object }
+        created_at: { type: string, format: date-time }
+        updated_at: { type: string, format: date-time }
+
+    ShipmentCreate:
+      type: object
+      required: [projectId, targetEnv]
+      properties:
+        projectId: { $ref: '#/components/schemas/UUID' }
+        agentId: { $ref: '#/components/schemas/UUID' }
+        targetEnv: { type: string }
+        payload: { type: object }
+
+    AiJob:
+      type: object
+      properties:
+        id: { $ref: '#/components/schemas/UUID' }
+        tenant_id: { $ref: '#/components/schemas/UUID' }
+        project_id: { $ref: '#/components/schemas/UUID', nullable: true }
+        entity_type: { type: string, nullable: true }
+        entity_id: { $ref: '#/components/schemas/UUID', nullable: true }
+        job_type: { type: string }
+        input_hash: { type: string, nullable: true }
+        output_hash: { type: string, nullable: true }
+        model_id: { type: string, nullable: true }
+        prompt_version: { type: string, nullable: true }
+        confidence_score: { type: number, nullable: true }
+        status: { type: string, enum: [pending, running, completed, failed, cancelled] }
+        input: { type: object }
+        output: { type: object, nullable: true }
+        created_at: { type: string, format: date-time }
+        updated_at: { type: string, format: date-time }
+        attempts: { type: integer }
+        last_error: { type: string, nullable: true }
+
+    AiJobCreate:
+      type: object
+      required: [jobType, input]
+      properties:
+        jobType: { type: string }
+        projectId: { $ref: '#/components/schemas/UUID' }
+        entityType: { type: string }
+        entityId: { $ref: '#/components/schemas/UUID' }
+        input: { type: object }
+        modelId: { type: string }
+        promptVersion: { type: string }
+      example:
+        jobType: "generate_frame"
+        input:
+          prompt: "Create a promotional Farcaster frame for a summer drop"
+
+    MarketListing:
+      type: object
+      properties:
+        id: { $ref: '#/components/schemas/UUID' }
+        tenant_id: { $ref: '#/components/schemas/UUID' }
+        template_id: { $ref: '#/components/schemas/UUID' }
+        seller_id: { $ref: '#/components/schemas/UUID' }
+        price_wei: { type: string }
+        status: { type: string, enum: [active, sold, cancelled] }
+        created_at: { type: string, format: date-time }
+        updated_at: { type: string, format: date-time }
+
+    MarketListingCreate:
+      type: object
+      required: [templateId, priceWei]
+      properties:
+        templateId: { $ref: '#/components/schemas/UUID' }
+        priceWei: { type: string }
+
+    Quest:
+      type: object
+      properties:
+        id: { $ref: '#/components/schemas/UUID' }
+        tenant_id: { $ref: '#/components/schemas/UUID' }
+        slug: { type: string }
+        title: { type: string }
+        description: { type: string }
+        type: { type: string }
+        criteria: { type: object }
+        reward_points: { type: integer }
+        start_at: { type: string, format: date-time, nullable: true }
+        end_at: { type: string, format: date-time, nullable: true }
+        created_at: { type: string, format: date-time }
+
+    Achievement:
+      type: object
+      properties:
+        id: { $ref: '#/components/schemas/UUID' }
+        tenant_id: { $ref: '#components/schemas/UUID' }
+        slug: { type: string }
+        title: { type: string }
+        description: { type: string }
+        icon: { type: string }
+        criteria: { type: object }
+        created_at: { type: string, format: date-time }
+
+    LeaderboardEntry:
+      type: object
+      properties:
+        id: { type: integer }
+        tenant_id: { $ref: '#/components/schemas/UUID' }
+        user_id: { $ref: '#/components/schemas/UUID' }
+        score: { type: integer }
+        period: { type: string, enum: [daily, weekly, all_time] }
+        period_start: { type: string, format: date-time }
+        period_end: { type: string, format: date-time }
+        updated_at: { type: string, format: date-time }
+
+    Follow:
+      type: object
+      properties:
+        id: { $ref: '#/components/schemas/UUID' }
+        tenant_id: { $ref: '#/components/schemas/UUID' }
+        follower_id: { $ref: '#/components/schemas/UUID' }
+        followed_user_id: { $ref: '#/components/schemas/UUID', nullable: true }
+        followed_project_id: { $ref: '#/components/schemas/UUID', nullable: true }
+        created_at: { type: string, format: date-time }
+
+    Like:
+      type: object
+      properties:
+        id: { $ref: '#/components/schemas/UUID' }
+        tenant_id: { $ref: '#/components/schemas/UUID' }
+        user_id: { $ref: '#/components/schemas/UUID' }
+        project_id: { $ref: '#/components/schemas/UUID', nullable: true }
+        frame_template_id: { $ref: '#/components/schemas/UUID', nullable: true }
+        created_at: { type: string, format: date-time }
+
+    Wallet:
+      type: object
+      properties:
+        id: { $ref: '#/components/schemas/UUID' }
+        user_id: { $ref: '#/components/schemas/UUID' }
+        address: { type: string }
+        chain: { type: string }
+        created_at: { type: string, format: date-time }
+
+    Subscription:
+      type: object
+      properties:
+        id: { $ref: '#/components/schemas/UUID' }
+        tenant_id: { $ref: '#/components/schemas/UUID' }
+        provider: { type: string }
+        provider_customer_id: { type: string }
+        provider_subscription_id: { type: string }
+        plan: { type: string }
+        status: { type: string }
+        current_period_end: { type: string, format: date-time }
+        created_at: { type: string, format: date-time }
+        updated_at: { type: string, format: date-time }
+
+    Invoice:
+      type: object
+      properties:
+        id: { $ref: '#/components/schemas/UUID' }
+        tenant_id: { $ref: '#/components/schemas/UUID' }
+        provider_invoice_id: { type: string }
+        amount_cents: { type: integer }
+        currency: { type: string }
+        status: { type: string }
+        issued_at: { type: string, format: date-time }
+        paid_at: { type: string, format: date-time, nullable: true }
+
+    AuditLog:
+      type: object
+      properties:
+        id: { type: integer }
+        tenant_id: { $ref: '#/components/schemas/UUID' }
+        user_id: { type: integer, nullable: true }
+        action: { type: string }
+        entity_type: { type: string }
+        entity_id: { $ref: '#/components/schemas/UUID', nullable: true }
+        metadata: { type: object }
+        ip: { type: string, format: ipv4, nullable: true }
+        created_at: { type: string, format: date-time }
+        immutable_seq: { type: integer }
+
+    ProtocolToken:
+      type: object
+      properties:
+        id: { $ref: '#/components/schemas/UUID' }
+        symbol: { type: string }
+        chain_id: { type: integer }
+        contract_address: { type: string }
+        decimals: { type: integer }
+        created_at: { type: string, format: date-time }
+
+    ProtocolFee:
+      type: object
+      properties:
+        id: { $ref: '#/components/schemas/UUID' }
+        tenant_id: { $ref: '#/components/schemas/UUID', nullable: true }
+        fee_type: { type: string }
+        bps: { type: integer }
+        max_bps: { type: integer }
+        updated_by: { $ref: '#/components/schemas/UUID' }
+        updated_at: { type: string, format: date-time }
+
+    ProtocolMetricsSnapshot:
+      type: object
+      properties:
+        id: { type: integer }
+        tenant_id: { $ref: '#/components/schemas/UUID', nullable: true }
+        timestamp: { type: string, format: date-time }
+        tvl_usd: { type: number }
+        volume_24h_usd: { type: number }
+        active_users_24h: { type: integer }
+        frames_active: { type: integer }
+        mints_24h: { type: integer }
+
+    SystemHealthCheck:
+      type: object
+      properties:
+        id: { type: integer }
+        timestamp: { type: string, format: date-time }
+        component: { type: string }
+        status: { type: string, enum: [healthy, degraded, down] }
+        latency_ms: { type: integer }
+        metadata: { type: object }
+
+    FeedItem:
+      type: object
+      properties:
+        id: { $ref: '#/components/schemas/UUID' }
+        tenant_id: { $ref: '#/components/schemas/UUID' }
+        type: { type: string }
+        payload: { type: object }
+        created_at: { type: string, format: date-time }
+
+    AnalyticsOverview:
+      type: object
+      properties:
+        views_24h: { type: integer }
+        mints_24h: { type: integer }
+        revenue_24h_usd: { type: number }
+        active_users_24h: { type: integer }
+        frames_active: { type: integer }
+
+    PaginatedFrameTemplates:
+      type: object
+      properties:
+        items:
+          type: array
+          items:
+            $ref: '#/components/schemas/FrameTemplate'
+        total: { type: integer }
+
+examples:
+  AiJobCreateExample:
+    value:
+      jobType: "generate_frame"
+      projectId: "00000000-0000-0000-0000-000000000000"
+      input:
+        prompt: "Design a Farcaster frame for a drop, include title, subtitle, CTA and image placeholders"
+  AiJobResponseExample:
+    value:
+      id: "11111111-1111-1111-1111-111111111111"
+      job_type: "generate_frame"
+      status: "completed"
+      input:
+        prompt: "Design a Farcaster frame for a drop"
+      output:
+        schema:
+          title: "Summer Drop"
+          subtitle: "Limited Edition"
+          cta: "Mint Now"
+          elements:
+            - type: "image"
+              url: "ipfs://..."
+      created_at: "2026-01-13T12:00:00Z"
+      updated_at: "2026-01-13T12:00:10Z"
+
+# TODO: further expand examples and per-path response bodies
+
*** End Patch
*** Begin Patch
*** Add File: infra/openapi/README.md
+# OpenAPI - CastQuest Full API
+
+Location:
+- infra/openapi/castquest-full-openapi.yaml
+
+Purpose:
+- Single source of truth for API surface for the gateway and downstream services.
+- Use to generate SDKs and API docs.
+
+Suggested regeneration steps for TypeScript types:
+1. Install openapi-typescript:
+   npm i -D openapi-typescript
+2. Generate types:
+   npx openapi-typescript infra/openapi/castquest-full-openapi.yaml --output packages/sdk/src/generated/types.ts
+
+To generate a full client with openapi-generator:
+- Install openapi-generator and run generation targeting TypeScript-Axios or other generators.
+
+Notes:
+- The current YAML is a working baseline; expand component schemas and examples as needed.
+
*** End Patch
*** Begin Patch
*** Add File: packages/sdk/package.json
+{
+  "name": "@castquest/sdk-starter",
+  "version": "0.1.0",
+  "description": "Typed TypeScript fetch client for CastQuest (starter). Generated from infra/openapi/castquest-full-openapi.yaml",
+  "main": "dist/index.js",
+  "types": "dist/index.d.ts",
+  "scripts": {
+    "build": "tsc -p tsconfig.json",
+    "clean": "rimraf dist",
+    "prepare": "npm run build"
+  },
+  "dependencies": {},
+  "devDependencies": {
+    "cross-fetch": "^3.1.5",
+    "typescript": "^4.9.5",
+    "rimraf": "^3.0.2"
+  }
+}
+
*** End Patch
*** Begin Patch
*** Add File: packages/sdk/tsconfig.json
+{
+  "compilerOptions": {
+    "target": "ES2019",
+    "module": "CommonJS",
+    "declaration": true,
+    "outDir": "dist",
+    "strict": true,
+    "esModuleInterop": true,
+    "skipLibCheck": true
+  },
+  "include": ["src/**/*"]
+}
+
*** End Patch
*** Begin Patch
*** Add File: packages/sdk/src/generated/types.ts
+/* Minimal type subset generated from OpenAPI components for starter SDK.
+   Extend when regenerating from the full OpenAPI file.
+*/
+export type UUID = string;
+
+export interface User {
+  id: UUID;
+  tenant_id: UUID;
+  email?: string;
+  username?: string;
+  display_name?: string;
+  role?: string;
+  created_at?: string;
+}
+
+export interface Tenant {
+  id: UUID;
+  slug?: string;
+  name?: string;
+  plan?: string;
+  created_at?: string;
+}
+
+export interface AiJob {
+  id: UUID;
+  tenant_id?: UUID;
+  project_id?: UUID;
+  entity_type?: string;
+  entity_id?: UUID;
+  job_type?: string;
+  status?: string;
+  input?: any;
+  output?: any;
+  created_at?: string;
+  updated_at?: string;
+}
+
+export interface FrameTemplate {
+  id: UUID;
+  project_id?: UUID;
+  tenant_id?: UUID;
+  name?: string;
+  description?: string;
+  current_version_id?: UUID;
+  created_by?: UUID;
+  created_at?: string;
+}
+
+export interface Project {
+  id: UUID;
+  tenant_id?: UUID;
+  owner_id?: UUID;
+  name?: string;
+  slug?: string;
+  description?: string;
+  visibility?: string;
+  created_at?: string;
+  updated_at?: string;
+}
+
*** End Patch
*** Begin Patch
*** Add File: packages/sdk/src/index.ts
+import fetch, { HeadersInit } from "cross-fetch";
+import { AiJob, FrameTemplate, Project, User, Tenant } from "./generated/types";
+
+export interface ClientOptions {
+  baseUrl?: string;
+  apiKey?: string; // optional: API key or use bearer token on request
+  fetchImpl?: typeof fetch;
+}
+
+export class CastQuestClient {
+  baseUrl: string;
+  apiKey?: string;
+  fetchImpl: typeof fetch;
+
+  constructor(options?: ClientOptions) {
+    this.baseUrl = options?.baseUrl ?? "http://localhost:8080";
+    this.apiKey = options?.apiKey;
+    this.fetchImpl = options?.fetchImpl ?? fetch;
+  }
+
+  private headers(extra?: HeadersInit, auth?: string) {
+    const h: HeadersInit = {
+      "Content-Type": "application/json",
+      ...extra,
+    };
+    if (this.apiKey) h["X-API-Key"] = this.apiKey;
+    if (auth) h["Authorization"] = `Bearer ${auth}`;
+    return h;
+  }
+
+  // Auth convenience: set bearer token for subsequent calls
+  public withAuth(token: string) {
+    return new AuthenticatedClient(this, token);
+  }
+
+  // Projects
+  async listProjects(limit = 20, offset = 0): Promise<{ items: Project[]; total: number }> {
+    const res = await this.fetchImpl(`${this.baseUrl}/projects?limit=${limit}&offset=${offset}`, {
+      method: "GET",
+      headers: this.headers(),
+    });
+    if (!res.ok) throw new Error(`listProjects failed: ${res.statusText}`);
+    return res.json();
+  }
+
+  async createProject(body: { name: string; description?: string; visibility?: string }): Promise<Project> {
+    const res = await this.fetchImpl(`${this.baseUrl}/projects`, {
+      method: "POST",
+      headers: this.headers(),
+      body: JSON.stringify(body),
+    });
+    if (!res.ok) throw new Error(`createProject failed: ${res.statusText}`);
+    return res.json();
+  }
+
+  // Frames
+  async listFrameTemplates(projectId?: string) {
+    const url = new URL(`${this.baseUrl}/frames/templates`);
+    if (projectId) url.searchParams.set("projectId", projectId);
+    const res = await this.fetchImpl(url.toString(), {
+      method: "GET",
+      headers: this.headers(),
+    });
+    if (!res.ok) throw new Error(`listFrameTemplates failed: ${res.statusText}`);
+    return res.json();
+  }
+
+  async createFrameTemplate(body: { projectId: string; name: string; description?: string; initialSchema: any }): Promise<FrameTemplate> {
+    const res = await this.fetchImpl(`${this.baseUrl}/frames/templates`, {
+      method: "POST",
+      headers: this.headers(),
+      body: JSON.stringify(body),
+    });
+    if (!res.ok) throw new Error(`createFrameTemplate failed: ${res.statusText}`);
+    return res.json();
+  }
+
+  // AI jobs (create and get)
+  async createAiJob(body: { jobType: string; projectId?: string; entityType?: string; entityId?: string; input: any; modelId?: string; promptVersion?: string }): Promise<AiJob> {
+    const res = await this.fetchImpl(`${this.baseUrl}/ai/jobs`, {
+      method: "POST",
+      headers: this.headers(),
+      body: JSON.stringify(body),
+    });
+    if (!res.ok) throw new Error(`createAiJob failed: ${res.statusText}`);
+    return res.json();
+  }
+
+  async getAiJob(jobId: string): Promise<AiJob> {
+    const res = await this.fetchImpl(`${this.baseUrl}/ai/jobs/${jobId}`, {
+      method: "GET",
+      headers: this.headers(),
+    });
+    if (!res.ok) throw new Error(`getAiJob failed: ${res.statusText}`);
+    return res.json();
+  }
+}
+
+class AuthenticatedClient {
+  client: CastQuestClient;
+  token: string;
+  constructor(client: CastQuestClient, token: string) {
+    this.client = client;
+    this.token = token;
+  }
+
+  private headers(extra?: HeadersInit) {
+    return this.client["headers"](extra, this.token);
+  }
+
+  // Example: wrap createFrameTemplate with auth
+  async createFrameTemplate(body: { projectId: string; name: string; description?: string; initialSchema: any }) {
+    const res = await this.client.fetchImpl(`${this.client.baseUrl}/frames/templates`, {
+      method: "POST",
+      headers: this.headers(),
+      body: JSON.stringify(body),
+    });
+    if (!res.ok) throw new Error(`createFrameTemplate failed: ${res.statusText}`);
+    return res.json();
+  }
+
+  async createAiJob(body: { jobType: string; projectId?: string; entityType?: string; entityId?: string; input: any; modelId?: string; promptVersion?: string }) {
+    return this.client.createAiJob(body); // uses base headers via client; no duplicate code for simple calls
+  }
+
+  async getAiJob(jobId: string) {
+    return this.client.getAiJob(jobId);
+  }
+}
+
+export { CastQuestClient, AuthenticatedClient, User, Tenant, AiJob, FrameTemplate, Project };
+
*** End Patch
*** Begin Patch
*** Add File: packages/sdk/src/examples/frame-builder.ts
+/**
+ * Example: Frame Builder flow using the starter SDK
+ *
+ * Steps:
+ * 1. POST /ai/jobs (jobType='generate_frame') with prompt -> returns job id
+ * 2. Poll GET /ai/jobs/:id until status === 'completed'
+ * 3. POST /frames/templates (create template) using AI output
+ * 4. POST /frames/templates/:id/versions (create version)
+ * 5. POST /frames/templates/:id/deploy (deploy)
+ *
+ * Run this script after building the SDK (node dist/examples/frame-builder.js)
+ */
+import { CastQuestClient } from "../index";
+
+async function runExample() {
+  const client = new CastQuestClient({ baseUrl: process.env.CQ_BASE_URL ?? "http://localhost:8080" });
+  // If you have a bearer token, use client.withAuth(token)
+  // const authClient = client.withAuth("YOUR_JWT");
+
+  // Step 1: Create AI job
+  const aiJob = await client.createAiJob({
+    jobType: "generate_frame",
+    input: {
+      prompt: "Create a promotional farcaster frame with title 'Summer Drop' and CTA 'Mint Now'",
+      constraints: { maxElements: 5 }
+    }
+  });
+  console.log("AI job created:", aiJob.id);
+
+  // Step 2: Poll job
+  const maxAttempts = 30;
+  let attempts = 0;
+  let job = aiJob;
+  while (attempts < maxAttempts) {
+    job = await client.getAiJob(aiJob.id);
+    console.log(`Polling job status: ${job.status}`);
+    if (job.status === "completed") break;
+    if (job.status === "failed") throw new Error("AI job failed: " + JSON.stringify(job.output));
+    attempts++;
+    await new Promise((r) => setTimeout(r, 2000));
+  }
+  if (job.status !== "completed") throw new Error("AI job did not complete in time");
+
+  const generatedSchema = job.output?.schema ?? { title: "Generated Frame", body: "Default" };
+
+  // Step 3: Create a new frame template (example projectId must exist)
+  const projectId = process.env.CQ_PROJECT_ID!;
+  if (!projectId) throw new Error("Set CQ_PROJECT_ID to an existing project id to run example");
+
+  const template = await client.createFrameTemplate({
+    projectId,
+    name: "AI Generated Frame - Example",
+    description: "Generated by AI job " + aiJob.id,
+    initialSchema: generatedSchema
+  });
+  console.log("Template created:", template.id);
+
+  // NOTE: Further steps (create versions, deploy) would follow similarly using the SDK calls.
+}
+
+runExample().catch((err) => {
+  console.error(err);
+  process.exit(1);
+});
+
*** End Patch
*** Begin Patch
*** Add File: packages/sdk/README.md
+# @castquest/sdk-starter
+
+This is a lightweight TypeScript fetch-based client for CastQuest. It is a starter client generated from infra/openapi/castquest-full-openapi.yaml.
+
+Usage
+1. Build:
+   npm install
+   npm run build
+
+2. Example:
+   Set CQ_BASE_URL and CQ_PROJECT_ID then run:
+   node dist/examples/frame-builder.js
+
+Regeneration
+- To regenerate types & client from the OpenAPI file, you can:
+  - Use openapi-typescript to generate types
+  - Or use openapi-generator to produce a client, then adapt to the fetch wrapper pattern used here.
+
+Recommended commands:
+- npx openapi-typescript infra/openapi/castquest-full-openapi.yaml --output src/generated/types.ts
+- Then adapt src/index.ts to call the typed interfaces.
+
+Notes
+- This starter client is dependency-light and uses cross-fetch for the example runtime.
+- Add authentication via `client.withAuth(token)` to include bearer token in requests.
+
*** End Patch
*** Begin Patch
*** Add File: infra/db/migrations/0001_create_tenants_users.sql
+-- 0001_create_tenants_users.sql
+CREATE EXTENSION IF NOT EXISTS "pgcrypto";
+CREATE EXTENSION IF NOT EXISTS "citext";
+
+-- Tenants
+CREATE TABLE IF NOT EXISTS tenants (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  slug text NOT NULL UNIQUE,
+  name text NOT NULL,
+  plan text NOT NULL DEFAULT 'free',
+  created_at timestamptz NOT NULL DEFAULT now(),
+  updated_at timestamptz NOT NULL DEFAULT now()
+);
+
+-- Users
+CREATE TABLE IF NOT EXISTS users (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
+  email citext,
+  username text,
+  display_name text,
+  avatar_url text,
+  role text NOT NULL DEFAULT 'user',
+  github_id text,
+  wallet_address text,
+  created_at timestamptz NOT NULL DEFAULT now(),
+  updated_at timestamptz NOT NULL DEFAULT now(),
+  UNIQUE (tenant_id, email)
+);
+
+CREATE INDEX IF NOT EXISTS idx_users_tenant ON users(tenant_id);
+
*** End Patch
*** Begin Patch
*** Add File: infra/db/migrations/0002_auth_sessions_apikeys.sql
+-- 0002_auth_sessions_apikeys.sql
+
+-- Auth identities
+CREATE TABLE IF NOT EXISTS auth_identities (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
+  provider text NOT NULL,
+  provider_user_id text NOT NULL,
+  metadata jsonb,
+  created_at timestamptz NOT NULL DEFAULT now()
+);
+
+-- Sessions
+CREATE TABLE IF NOT EXISTS sessions (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
+  refresh_token_hash text UNIQUE,
+  expires_at timestamptz NOT NULL,
+  user_agent text,
+  ip inet,
+  created_at timestamptz NOT NULL DEFAULT now(),
+  revoked_at timestamptz
+);
+CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
+
+-- API keys
+CREATE TABLE IF NOT EXISTS api_keys (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
+  user_id uuid NOT NULL REFERENCES users(id) ON DELETE SET NULL,
+  name text NOT NULL,
+  prefix text NOT NULL UNIQUE,
+  secret_hash text NOT NULL,
+  scopes text[],
+  last_used_at timestamptz,
+  created_at timestamptz NOT NULL DEFAULT now(),
+  revoked_at timestamptz
+);
+CREATE INDEX IF NOT EXISTS idx_api_keys_tenant ON api_keys(tenant_id);
+
*** End Patch
*** Begin Patch
*** Add File: infra/db/migrations/0003_projects_files.sql
+-- 0003_projects_files.sql
+
+-- Projects
+CREATE TABLE IF NOT EXISTS projects (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
+  owner_id uuid NOT NULL REFERENCES users(id) ON DELETE SET NULL,
+  name text NOT NULL,
+  slug text NOT NULL,
+  description text,
+  visibility text NOT NULL DEFAULT 'private',
+  default_branch text NOT NULL DEFAULT 'main',
+  created_at timestamptz NOT NULL DEFAULT now(),
+  updated_at timestamptz NOT NULL DEFAULT now(),
+  UNIQUE (tenant_id, slug)
+);
+CREATE INDEX IF NOT EXISTS idx_projects_tenant ON projects(tenant_id);
+
+-- Project members
+CREATE TABLE IF NOT EXISTS project_members (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
+  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
+  role text NOT NULL DEFAULT 'viewer',
+  created_at timestamptz NOT NULL DEFAULT now()
+);
+CREATE INDEX IF NOT EXISTS idx_project_members_project ON project_members(project_id);
+
+-- Files
+CREATE TABLE IF NOT EXISTS files (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
+  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
+  path text NOT NULL,
+  content text,
+  language text,
+  version int NOT NULL DEFAULT 1,
+  is_directory boolean NOT NULL DEFAULT false,
+  parent_id uuid,
+  created_at timestamptz NOT NULL DEFAULT now(),
+  updated_at timestamptz NOT NULL DEFAULT now()
+);
+CREATE INDEX IF NOT EXISTS idx_files_project_path ON files(project_id, path);
+
+-- File snapshots
+CREATE TABLE IF NOT EXISTS file_snapshots (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  file_id uuid NOT NULL REFERENCES files(id) ON DELETE CASCADE,
+  version int NOT NULL,
+  content text NOT NULL,
+  created_at timestamptz NOT NULL DEFAULT now(),
+  created_by uuid REFERENCES users(id)
+);
+CREATE INDEX IF NOT EXISTS idx_file_snapshots_file ON file_snapshots(file_id);
+
*** End Patch
*** Begin Patch
*** Add File: infra/db/migrations/0004_previews_agents_shipments.sql
+-- 0004_previews_agents_shipments.sql
+
+CREATE TABLE IF NOT EXISTS previews (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
+  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
+  compiled_bundle_url text,
+  iframe_url text,
+  last_build_status text,
+  last_build_log text,
+  created_at timestamptz NOT NULL DEFAULT now(),
+  updated_at timestamptz NOT NULL DEFAULT now()
+);
+
+CREATE TABLE IF NOT EXISTS agents (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
+  name text NOT NULL,
+  description text,
+  type text,
+  config jsonb,
+  is_active boolean NOT NULL DEFAULT true,
+  created_at timestamptz NOT NULL DEFAULT now(),
+  updated_at timestamptz NOT NULL DEFAULT now()
+);
+
+CREATE TABLE IF NOT EXISTS shipments (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
+  project_id uuid REFERENCES projects(id),
+  agent_id uuid REFERENCES agents(id),
+  status text NOT NULL DEFAULT 'pending',
+  target_env text,
+  payload jsonb,
+  result jsonb,
+  created_at timestamptz NOT NULL DEFAULT now(),
+  updated_at timestamptz NOT NULL DEFAULT now()
+);
+CREATE INDEX IF NOT EXISTS idx_shipments_project ON shipments(project_id);
+
*** End Patch
*** Begin Patch
*** Add File: infra/db/migrations/0005_frames_templates.sql
+-- 0005_frames_templates.sql
+
+CREATE TABLE IF NOT EXISTS frame_templates (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
+  project_id uuid REFERENCES projects(id),
+  name text NOT NULL,
+  description text,
+  current_version_id uuid,
+  farcaster_frame_id text,
+  created_by uuid REFERENCES users(id),
+  created_at timestamptz NOT NULL DEFAULT now(),
+  updated_at timestamptz NOT NULL DEFAULT now()
+);
+
+CREATE TABLE IF NOT EXISTS frame_template_versions (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  template_id uuid NOT NULL REFERENCES frame_templates(id) ON DELETE CASCADE,
+  version int NOT NULL,
+  schema jsonb NOT NULL,
+  status text NOT NULL DEFAULT 'draft',
+  change_summary text,
+  created_by uuid REFERENCES users(id),
+  created_at timestamptz NOT NULL DEFAULT now(),
+  UNIQUE (template_id, version)
+);
+
+CREATE TABLE IF NOT EXISTS frame_timelines (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
+  template_id uuid NOT NULL REFERENCES frame_templates(id) ON DELETE CASCADE,
+  version_id uuid,
+  event_type text,
+  metadata jsonb,
+  created_at timestamptz NOT NULL DEFAULT now(),
+  created_by uuid
+);
+
+CREATE INDEX IF NOT EXISTS idx_frame_timelines_template ON frame_timelines(template_id);
+
*** End Patch
*** Begin Patch
*** Add File: infra/db/migrations/0006_ai_jobs_tailors.sql
+-- 0006_ai_jobs_tailors.sql
+
+CREATE TABLE IF NOT EXISTS tailors (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
+  name text NOT NULL,
+  description text,
+  config jsonb,
+  created_at timestamptz NOT NULL DEFAULT now(),
+  updated_at timestamptz NOT NULL DEFAULT now()
+);
+
+CREATE TABLE IF NOT EXISTS ai_jobs (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
+  project_id uuid,
+  entity_type text,
+  entity_id uuid,
+  job_type text NOT NULL,
+  input_hash text,
+  output_hash text,
+  model_id text,
+  prompt_version text,
+  confidence_score numeric(5,4),
+  status text NOT NULL DEFAULT 'pending',
+  input jsonb NOT NULL,
+  output jsonb,
+  created_at timestamptz NOT NULL DEFAULT now(),
+  updated_at timestamptz NOT NULL DEFAULT now(),
+  attempts int NOT NULL DEFAULT 0,
+  last_error text
+);
+CREATE INDEX IF NOT EXISTS idx_ai_jobs_tenant_status ON ai_jobs(tenant_id, status);
+
*** End Patch
*** Begin Patch
*** Add File: infra/db/migrations/0007_market_mints_ledger.sql
+-- 0007_market_mints_ledger.sql
+
+CREATE TABLE IF NOT EXISTS markets_listings (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
+  template_id uuid NOT NULL REFERENCES frame_templates(id),
+  seller_id uuid NOT NULL REFERENCES users(id),
+  price_wei numeric(38,0) NOT NULL,
+  status text NOT NULL DEFAULT 'active',
+  created_at timestamptz NOT NULL DEFAULT now(),
+  updated_at timestamptz NOT NULL DEFAULT now()
+);
+
+CREATE TABLE IF NOT EXISTS mints (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
+  frame_id uuid REFERENCES frame_templates(id),
+  token_contract text NOT NULL,
+  token_id numeric(38,0) NOT NULL,
+  chain_id int NOT NULL,
+  minter_address text,
+  tx_hash text,
+  quantity numeric(38,0) DEFAULT 1,
+  price_paid_wei numeric(38,0),
+  created_at timestamptz NOT NULL DEFAULT now(),
+  UNIQUE (token_contract, token_id, chain_id)
+);
+CREATE INDEX IF NOT EXISTS idx_mints_tenant ON mints(tenant_id);
+
*** End Patch
*** Begin Patch
*** Add File: infra/db/migrations/0008_quests_achievements_leaderboard.sql
+-- 0008_quests_achievements_leaderboard.sql
+
+CREATE TABLE IF NOT EXISTS quests (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
+  slug text NOT NULL,
+  title text NOT NULL,
+  description text,
+  type text NOT NULL,
+  criteria jsonb NOT NULL,
+  reward_points int NOT NULL DEFAULT 0,
+  start_at timestamptz,
+  end_at timestamptz,
+  created_at timestamptz NOT NULL DEFAULT now(),
+  updated_at timestamptz NOT NULL DEFAULT now(),
+  UNIQUE (tenant_id, slug)
+);
+
+CREATE TABLE IF NOT EXISTS user_quest_progress (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
+  quest_id uuid NOT NULL REFERENCES quests(id) ON DELETE CASCADE,
+  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
+  progress jsonb NOT NULL DEFAULT '{}'::jsonb,
+  completed_at timestamptz,
+  updated_at timestamptz NOT NULL DEFAULT now(),
+  UNIQUE (quest_id, user_id)
+);
+
+CREATE TABLE IF NOT EXISTS achievements (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
+  slug text NOT NULL,
+  title text NOT NULL,
+  description text,
+  icon text,
+  criteria jsonb NOT NULL,
+  created_at timestamptz NOT NULL DEFAULT now(),
+  UNIQUE (tenant_id, slug)
+);
+
+CREATE TABLE IF NOT EXISTS user_achievements (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
+  achievement_id uuid NOT NULL REFERENCES achievements(id) ON DELETE CASCADE,
+  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
+  awarded_at timestamptz NOT NULL DEFAULT now()
+);
+
+CREATE TABLE IF NOT EXISTS leaderboard_entries (
+  id bigserial PRIMARY KEY,
+  tenant_id uuid REFERENCES tenants(id),
+  user_id uuid REFERENCES users(id),
+  score int NOT NULL DEFAULT 0,
+  period text NOT NULL,
+  period_start timestamptz,
+  period_end timestamptz,
+  updated_at timestamptz NOT NULL DEFAULT now()
+);
+CREATE INDEX IF NOT EXISTS idx_leaderboard_tenant_period ON leaderboard_entries(tenant_id, period, period_start);
+
*** End Patch
*** Begin Patch
*** Add File: infra/db/migrations/0009_protocol_audit_system.sql
+-- 0009_protocol_audit_system.sql
+
+CREATE TABLE IF NOT EXISTS protocol_tokens (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  symbol text NOT NULL,
+  chain_id int,
+  contract_address text,
+  decimals int,
+  created_at timestamptz NOT NULL DEFAULT now(),
+  updated_at timestamptz NOT NULL DEFAULT now()
+);
+
+CREATE TABLE IF NOT EXISTS protocol_fees (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  tenant_id uuid REFERENCES tenants(id),
+  fee_type text NOT NULL,
+  bps int NOT NULL,
+  max_bps int NOT NULL DEFAULT 1000,
+  updated_by uuid REFERENCES users(id),
+  updated_at timestamptz NOT NULL DEFAULT now()
+);
+
+CREATE TABLE IF NOT EXISTS protocol_metrics_snapshots (
+  id bigserial PRIMARY KEY,
+  tenant_id uuid REFERENCES tenants(id),
+  timestamp timestamptz NOT NULL DEFAULT now(),
+  tvl_usd numeric,
+  volume_24h_usd numeric,
+  active_users_24h int,
+  frames_active int,
+  mints_24h int
+);
+
+CREATE TABLE IF NOT EXISTS system_health_checks (
+  id bigserial PRIMARY KEY,
+  timestamp timestamptz NOT NULL DEFAULT now(),
+  component text NOT NULL,
+  status text NOT NULL,
+  latency_ms int,
+  metadata jsonb
+);
+
+CREATE TABLE IF NOT EXISTS audit_logs (
+  id bigserial PRIMARY KEY,
+  tenant_id uuid REFERENCES tenants(id),
+  user_id uuid,
+  action text NOT NULL,
+  entity_type text,
+  entity_id uuid,
+  metadata jsonb,
+  ip inet,
+  created_at timestamptz NOT NULL DEFAULT now(),
+  immutable_seq bigserial UNIQUE
+);
+CREATE INDEX IF NOT EXISTS idx_audit_logs_tenant ON audit_logs(tenant_id);
+
+-- TODO: Add RLS policies in PR #10
+
*** End Patch
*** Begin Patch
*** Add File: infra/db/migrations/0010_social_wallets.sql
+-- 0010_social_wallets.sql
+
+CREATE TABLE IF NOT EXISTS follows (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
+  follower_id uuid NOT NULL REFERENCES users(id),
+  followed_user_id uuid,
+  followed_project_id uuid,
+  created_at timestamptz NOT NULL DEFAULT now()
+);
+CREATE INDEX IF NOT EXISTS idx_follows_follower ON follows(follower_id);
+
+CREATE TABLE IF NOT EXISTS likes (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
+  user_id uuid NOT NULL REFERENCES users(id),
+  project_id uuid,
+  frame_template_id uuid,
+  created_at timestamptz NOT NULL DEFAULT now()
+);
+
+CREATE TABLE IF NOT EXISTS wallets (
+  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
+  user_id uuid NOT NULL REFERENCES users(id),
+  address text NOT NULL,
+  chain text,
+  created_at timestamptz NOT NULL DEFAULT now()
+);
+CREATE INDEX IF NOT EXISTS idx_wallets_user ON wallets(user_id);
+
*** End Patch
*** Begin Patch
*** Add File: infra/db/migrations/README.md
+# DB Migrations
+
+This directory contains SQL migrations to create the initial core schema.
+
+How to run:
+- Use your preferred migration tool (node-pg-migrate, Flyway, sqitch, knex migrations).
+- Example with psql:
+  psql $DATABASE_URL -f infra/db/migrations/0001_create_tenants_users.sql
+  psql $DATABASE_URL -f infra/db/migrations/0002_auth_sessions_apikeys.sql
+  ...
+
+Notes:
+- These migrations intentionally do not add Row Level Security (RLS). RLS policies will be added in PR #10.
+- The migrations use `pgcrypto` and `citext`. Ensure the DB allows creating extensions.
+- Index recommendations are included; revisit index choices after load testing.
+
*** End Patch
*** Begin Patch
*** Add File: infra/.github/workflows/openapi-sdk.yml
+name: OpenAPI Lint & SDK Build
+on:
+  pull_request:
+    paths:
+      - 'infra/openapi/**'
+      - 'packages/sdk/**'
+jobs:
+  lint-and-build:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with:
+          node-version: 18
+      - name: Install deps
+        run: |
+          cd packages/sdk
+          npm ci
+      - name: Build SDK
+        run: |
+          cd packages/sdk
+          npm run build
+      - name: Lint OpenAPI (optional)
+        run: |
+          if ! command -v @readme/openapi-cli >/dev/null 2>&1; then npm i -g @readme/openapi-cli; fi
+          openapi validate infra/openapi/castquest-full-openapi.yaml || true
+
*** End Patch
*** Begin Patch
*** Add File: PR_DESCRIPTION.md
+# PR: Add full OpenAPI spec, TypeScript SDK starter, and initial DB migrations
+
+This Draft PR adds:
+- infra/openapi/castquest-full-openapi.yaml — expanded OpenAPI 3.0.3 spec covering auth, projects, frames, agents, shipments, billing, ai, admin, dev-api, market, quests, social, analytics.
+- packages/sdk — TypeScript SDK starter (typed fetch client), minimal generated types, example usage for the Frame Builder flow, and README.
+- infra/db/migrations/0001_... -> 0010_... — initial numbered SQL migrations creating core schema.
+- infra/openapi/README.md explaining regeneration steps.
+- infra/.github/workflows/openapi-sdk.yml CI workflow (builds SDK and validates OpenAPI).
+
+Follow-ups:
+- PR #9: UI wiring + tests (apps/web + apps/admin integration using the new SDK)
+- PR #10: Finalize DB migrations with RLS policies, index tuning, and RLS tests
+
+Notes:
+- Migrations do not include Row Level Security (RLS); add RLS in PR #10 and add RLS policies that use current_setting('app.tenant_id')::uuid pattern.
+- The OpenAPI file is a baseline; expand component schemas and examples as you iterate.
+
*** End Patch
PATCH

# 4) apply the patch
echo "Applying patch..."
# ensure patch tool compatibility: try git apply
if git apply --verbose "$PATCH_FILE"; then
  echo "Patch applied (git apply)."
else
  echo "git apply failed; trying 'git apply --index'..."
  git apply --index "$PATCH_FILE"
fi

# 5) create branch and commit
git checkout -b "$BRANCH"
git add -A
git commit -m "$COMMIT_MSG"

# 6) push branch
git push --set-upstream origin "$BRANCH"

# 7) create PR if gh installed
if command -v gh >/dev/null 2>&1; then
  # ensure PR description file exists (we created it as part of the patch)
  if [[ ! -f "$PR_BODY_FILE" ]]; then
    echo "PR description file $PR_BODY_FILE not found; creating minimal body."
    cat > "$PR_BODY_FILE" <<EOF
Add full OpenAPI spec, TypeScript SDK starter, and initial DB migrations (PR #8)

This is a Draft PR. Follow-ups:
- PR #9: UI wiring + tests
- PR #10: DB migrations + RLS
EOF
  fi

  echo "Creating Draft PR on GitHub using gh..."
  gh pr create --title "$PR_TITLE" --body-file "$PR_BODY_FILE" --base main --head "$BRANCH" --draft
  echo "Draft PR created."
else
  echo "gh CLI not found. Branch pushed: $BRANCH"
  echo "To create a Draft PR, run:"
  echo "  gh pr create --title \"$PR_TITLE\" --body-file $PR_BODY_FILE --base main --head $BRANCH --draft"
  echo "Or open GitHub web UI and create a PR from branch $BRANCH -> main, and mark it as Draft."
fi

echo "Done."
