/**
 * Example: Frame Builder flow using the starter SDK
 *
 * Steps:
 * 1. POST /ai/jobs (jobType='generate_frame') with prompt -> returns job id
 * 2. Poll GET /ai/jobs/:id until status === 'completed'
 * 3. POST /frames/templates (create template) using AI output
 * 4. POST /frames/templates/:id/versions (create version)
 * 5. POST /frames/templates/:id/deploy (deploy)
 *
 * Run this script after building the SDK (node dist/examples/frame-builder.js)
 */
import { CastQuestClient } from "../index";

async function runExample() {
  const client = new CastQuestClient({ baseUrl: process.env.CQ_BASE_URL ?? "http://localhost:8080" });
  // If you have a bearer token, use client.withAuth(token)
  // const authClient = client.withAuth("YOUR_JWT");

  // Step 1: Create AI job
  const aiJob = await client.createAiJob({
    jobType: "generate_frame",
    input: {
      prompt: "Create a promotional farcaster frame with title 'Summer Drop' and CTA 'Mint Now'",
      constraints: { maxElements: 5 }
    }
  });
  console.log("AI job created:", aiJob.id);

  // Step 2: Poll job
  const maxAttempts = 30;
  let attempts = 0;
  let job = aiJob;
  while (attempts < maxAttempts) {
    job = await client.getAiJob(aiJob.id);
    console.log(`Polling job status: ${job.status}`);
    if (job.status === "completed") break;
    if (job.status === "failed") throw new Error("AI job failed: " + JSON.stringify(job.output));
    attempts++;
    await new Promise((r) => setTimeout(r, 2000));
  }
  if (job.status !== "completed") throw new Error("AI job did not complete in time");

  const generatedSchema = job.output?.schema ?? { title: "Generated Frame", body: "Default" };

  // Step 3: Create a new frame template (example projectId must exist)
  const projectId = process.env.CQ_PROJECT_ID!;
  if (!projectId) throw new Error("Set CQ_PROJECT_ID to an existing project id to run example");

  const template = await client.createFrameTemplate({
    projectId,
    name: "AI Generated Frame - Example",
    description: "Generated by AI job " + aiJob.id,
    initialSchema: generatedSchema
  });
  console.log("Template created:", template.id);

  // NOTE: Further steps (create versions, deploy) would follow similarly using the SDK calls.
}

runExample().catch((err) => {
  console.error(err);
  process.exit(1);
});
